# fly.toml app configuration file generated for phonebook123 on 2024-05-08T15:22:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook123'
primary_region = 'sea'

[env]
  PORT = "3000" 

[processes]
  frontend = "npm run serve"
  backend = "npm start"

[http_service]
  internal_port = 3000 
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["frontend", "backend" ]

[[services]]
  internal_port = 3000 
  protocol = "tcp"
  processes = ["frontend"]

[[services.ports]]
 handlers = ["http"]
  port = 3000

[[services]]
  internal_port = 3001 # 
  protocol = "tcp"
  processes = ["backend"]

[[services.ports]]
  handlers = ["http"]
  port = 3001

[build]
  dockerfile = "Dockerfile"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
